version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/UniGetUI"
    schedule:
      interval: "weekly"
    groups:
      all-nuget-updates:
        patterns:
          - "*"
