name: Publish prereleases to WinGet

on:
  release:
    types: [published]  # Trigger on published release (includes prereleases)
  workflow_dispatch:

jobs:
  publish:
    if: github.event.release.prerelease == true  # Ensure this only runs for prereleases
    runs-on: ubuntu-latest

    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@b3a5dae0047c6180023acba3f548c55fdf6b7193
        with:
          identifier: MartiCliment.UniGetUI.Pre-Release
          installers-regex: 'UniGetUI\.Installer\.exe$'
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
